require 'chairs_factory'
require 'chairs_factory/factory_callbacks'
require 'chairs_factory/factory_customizer'
require 'chairs_factory/factory_declarator'
require 'chairs_factory/factory_instance'
require 'chairs_factory/factory'
