require 'factory_boy'
require 'factory_boy/factory_callbacks'
require 'factory_boy/factory_customizer'
require 'factory_boy/factory_declarator'
require 'factory_boy/factory_instance'
require 'factory_boy/factory'
